# uBlacklist DSL file
# - Author: Sigsign <sig@signote.cc>
# - License: MIT-0

#
# Added on 2024/06/27
#
block "pentanews.net"
block "seidentest.com"
block "lagcapa.org"
block "anogate.jp"
block "xn--u9j5h1btf1ez99qnszei5c8ws.com" # 芸能人の裏ニュース.com
block "minorie.com"
block "shimashima01.net"
block "syotiku9910.com"
block "yuu01.jp"
block "kanata12.com"
block "yukiq.com"
block "nancreator.com"
block "pimmsofficial.com"
block "mochiyuru-life.com"
block "linart.net"
block "yura-time.com"
block "geinouzin.net"
block "hiramine.xyz"
block "rank1-media.com"
block "miima.jp"
block "bibi-star.jp"
block "vtuberinfo.net"
block "digitaldiy.jp"
block "himmel-ellipse.com"
block "xr-hub.com"
block "isyokuju.com"
block "alpinearagon.com"
block "gakumaji.com"
block "v-link-world.com"
block "youtubermemories.com"
block "popnews.info"
block "paradeparade.jp"
block "iwatekko.jp"
block "haikara-syokudo.jp"
block "caso-gallery.jp"
block "one-search.net"
block "kururing.info"
block "cheat-sokuhou.com"
block "endia.net"
block "pizzaofrock.com"
block "success-sword.com"
block "jonathan-movie.jp"
block "taiblo.jp"
block "takamatsu-webmuseum.jp"
block "tenbus.info"
block "matome-new.com"
block "mutyun.com"
block "fgo-babylonia-cafe.jp"
block "vtuber-matomeblog.com"
block "vtubernews.jp"
block "holosoku.com"
block "vtuber-matomeruyon.blog.jp", withoutSubdomain: true
block "nakamiya120719.livedoor.blog", withoutSubdomain: true
block "vtuber-newsmtm.blog.jp", withoutSubdomain: true
block "asbelllrin.livedoor.blog", withoutSubdomain: true
block "kokopyon.net"
block "unkochan893.com"
block "oomonoyoutubersokuhou.blogo.jp", withoutSubdomain: true
block "vtuber-nijihoro.blog.jp", withoutSubdomain: true
block "coolpan.net"
block "fire5ch.com"
block "asamuch.com"
block "gtk122.com"
block "doujinsokuhou45.com"
block "gamejksokuhou.com"
block "tsuchiyatasuku.livedoor.blog", withoutSubdomain: true
block "holo-news.com"
block "nan-nan.blog.jp", withoutSubdomain: true
block "vtubersokuhou.blog.jp", withoutSubdomain: true
block "tarosoku.com"
block "hakkisi.blog.fc2.com", withoutSubdomain: true
block "joker004.blog.fc2.com", withoutSubdomain: true
block "matomedane.jp"
block "1blog.jp"
block "rumors.sub.jp", withoutSubdomain: true
block "comedydouga.com"
block "5chmap.com"
block "antenam.jp"
block "2ch-c.net"
block "ngo-antenna.com"
block "atodeyo.com"
block "t-phantom.jp"
block "yaraon-blog.com"
block "softproinnovations.com"
block "phsmdcshineresidences.com"
block "espo-game.jp"
block "shootingbar-ea.jp"
block "wadainomori.net"
block "forest-life-japan.com"
block "menuguildsystem.com"
block "esuteru.com"
block "mangasokuhou.com"
block "h-guidepost.com"
block "aoimori-norin.jp"
block "ti-blg-02.com"
block "collieme.com"
block "sasa-blog42.com"
block "koregasiritai.com"
block "youbunkakuritsu.blogspot.com", withoutSubdomain: true
block "ashitanokioku.jp"
block "newsnachricht.net"
block_path "note.com/ppoch/*"
block "kossy-trend.com"
block "waiparavalleynz.com"
block "efire-matome.com"
block "akanbo-media.jp"
block "vyoutuber.com"
block "tuber-ch.com"
block "dyslexia-az.org"
block "nasupapa.com"
block "nijihorosokuvtubermatome.com"
block "ozakisagashite.jp"
block "psypuni7.com"
block "sknet-sougou.com"
block "vtuber-matome-media.com"
block "oyasukyo.jp"
block "cranq.jp"
block "youpress.jp"
block "emasora.com"
block "koe-voice.jp"
block "daisy-times.com"
block "soratobuiruka.com"
block "youkai-mago.com"
block "tamekatu.com"
block "anichoice.com"
block "trandays.com"
block "zaitakusyufu.net"
block "lefty322.com"
block "mattsu1015.com"
block "tennisblog.org"
block "kayuitokoronite.com"
block "academic-box.com"
block "pomomoy.com"
block "snsdays.com"
block "mayuhke.com"
block "mafi-blog.com"
block "xserver-1.com"
block "hinanoto.com"
block "rika333ep.com"
block "yamucollege.com"
block "newsunpia.com"
block "naomama-blog.com"
block "oritrenews.com"
block "kirisamehare.com"
block "ningennojikan.com"
block "brokker.jp"
block "sentou.jp"
block "tsuiran.jp"
block "livecafe-jive.com"
block "musubi10.com"
block "e-fugu.jp"
block "tatabi-sueblog.com"
block "matomame.jp"
block "sakidoritimes.jp"
block "obetokoshi.com"
block "matomesaito.jp"
block "nanjgod.com"
block "wb-otsuchi.com"
block "writer-life.com"
block "takuya-tyconist.jp"
block "sleepyboy0223.com"
block "hilokume.jp"
block "kataomoi3.com"
block "yu-trend.com"
block "unzen-amakusa.jp"
block "apexheadline.com"
block "academic-box.be"
block "hanesokunews.net"
block "maymay05.com"
block "digitalyouth.jp"
block "8mato.jp"
block "brownlind.xyz"
block "entertainment-topics.jp"
block "nikemaru.com"
block "rekisiru.com"
block "rebooto3.com"
block "coaweek.org"
block "monamona2525.com"
block "sottyann.com"
block "komatsushima-life.net"
block "frequ.jp"
block "tohyotalk.com"
block "drinkdsm.com"
block "legalbigbang.com"
block "ydenki.jp"
block "mini-memo.com"
block "asuoyama.jp"
block "topic-lab.com"
block "tokyo-animetourism.jp"
block "lab4g.net"
block "egao888.com"
block "nayami-sodan.net"
block "oshinisasageru.com"
block "mopumopu.com"
block "xn--j9j243ljipfhp.biz" # 知っ得袋.biz
block "yarukimanblg.com"
block "asakuravc.jp"
block "allaboutparadise.jp"
block "bokoguma.com"
block "hinachoice.com"
block "koku-byakunews.com"

# site is closed, but it still appears in search results
block "nyfco.org"
block "nicotubers.com"
block "prospectmedicalholdings.com"
block "youtubernews.net"
block "tuberz.net"
block "mitsuya-magazine.com"
block "valenciafashionweek.com"
block "blackshirts.info"
block "documentation-provence.org"
block "idahotvep.org"
block "cambridge-india.org"
block "iketog.com"
block "comisoku.com"
block "vnews.work"
block "vrtuber-news.com"
block "kurojou.com"
block "youtube5ch.com"
block "budou-game.com"
block "vtuber.matomemato.me"
block "vtuber-news.com"
block "jeep-m.jp"
block "vtuber-labo.com"
block "netsoku.com"
block "gotube.info"
block "artzone.jp"
block "nicolehappiness.com"
