# uBlacklist DSL file
# - Author: Sigsign <sig@signote.cc>
# - License: MIT-0

#
# Added on 2024/06/27
#
block "pentanews.net"
block "seidentest.com"
block "lagcapa.org"
block "anogate.jp"
block "xn--u9j5h1btf1ez99qnszei5c8ws.com" # 芸能人の裏ニュース.com
block "minorie.com"
block "shimashima01.net"
block "syotiku9910.com"
block "yuu01.jp"
block "aidoly.net"
block "kanata12.com"
block "yukiq.com"
block "nancreator.com"
block "pimmsofficial.com"
block "mochiyuru-life.com"
block "linart.net"
block "yura-time.com"
block "geinouzin.net"
block "aokiin.com"
block "hiramine.xyz"
block "rank1-media.com"
block "miima.jp"
block "bibi-star.jp"
block "vtuberinfo.net"
block "digitaldiy.jp"
block "himmel-ellipse.com"
block "xr-hub.com"
block "isyokuju.com"
block "alpinearagon.com"
block "gakumaji.com"
block "v-link-world.com"
block "youtubermemories.com"
block "popnews.info"
block "paradeparade.jp"
block "iwatekko.jp"
block "haikara-syokudo.jp"
block "caso-gallery.jp"
block "one-search.net"
block "kururing.info"
block "cheat-sokuhou.com"
block "endia.net"
block "pizzaofrock.com"
block "success-sword.com"
block "jonathan-movie.jp"
block "taiblo.jp"
block "takamatsu-webmuseum.jp"
block "tenbus.info"

# site is closed, but it still appears in search results
block "nyfco.org"
block "nicotubers.com"
block "prospectmedicalholdings.com"
block "youtubernews.net"
block "tuberz.net"
block "mitsuya-magazine.com"
block "valenciafashionweek.com"
block "blackshirts.info"
block "documentation-provence.org"
block "idahotvep.org"
block "cambridge-india.org"
block "iketog.com"
