# uBlacklist DSL file
# - Author: Sigsign <sig@signote.cc>
# - License: MIT-0

#
# Added on 2024/06/27
#
block "pentanews.net"
block "seidentest.com"
block "lagcapa.org"
block "anogate.jp"
block "xn--u9j5h1btf1ez99qnszei5c8ws.com" # 芸能人の裏ニュース.com
block "minorie.com"
block "shimashima01.net"
block "syotiku9910.com"
block "yuu01.jp"
block "aidoly.net"
block "kanata12.com"
block "yukiq.com"
block "nancreator.com"
block "pimmsofficial.com"
block "mochiyuru-life.com"
block "linart.net"
block "yura-time.com"
block "geinouzin.net"
block "aokiin.com"
block "hiramine.xyz"
block "rank1-media.com"
block "miima.jp"
block "bibi-star.jp"
block "vtuberinfo.net"
block "digitaldiy.jp"
block "himmel-ellipse.com"
block "xr-hub.com"
block "isyokuju.com"
block "alpinearagon.com"
block "gakumaji.com"
block "v-link-world.com"
block "youtubermemories.com"
block "popnews.info"
block "paradeparade.jp"
block "iwatekko.jp"
block "haikara-syokudo.jp"
block "caso-gallery.jp"
block "one-search.net"
block "kururing.info"
block "cheat-sokuhou.com"
block "endia.net"
block "pizzaofrock.com"
block "success-sword.com"
block "jonathan-movie.jp"
block "taiblo.jp"
block "takamatsu-webmuseum.jp"
block "tenbus.info"
block "matome-new.com"
block "mutyun.com"
block "fgo-babylonia-cafe.jp"
block "vtuber-matomeblog.com"
block "vtubernews.jp"
block "holosoku.com"
block "vtuber-matomeruyon.blog.jp", withoutSubdomain: true
block "nakamiya120719.livedoor.blog", withoutSubdomain: true
block "vtuber-newsmtm.blog.jp", withoutSubdomain: true
block "asbelllrin.livedoor.blog", withoutSubdomain: true
block "kokopyon.net"
block "unkochan893.com"
block "oomonoyoutubersokuhou.blogo.jp", withoutSubdomain: true
block "vtuber-nijihoro.blog.jp", withoutSubdomain: true
block "coolpan.net"
block "fire5ch.com"
block "asamuch.com"
block "gtk122.com"
block "doujinsokuhou45.com"
block "gamejksokuhou.com"
block "tsuchiyatasuku.livedoor.blog", withoutSubdomain: true
block "holo-news.com"
block "nan-nan.blog.jp", withoutSubdomain: true
block "vtubersokuhou.blog.jp", withoutSubdomain: true
block "tarosoku.com"
block "hakkisi.blog.fc2.com", withoutSubdomain: true
block "joker004.blog.fc2.com", withoutSubdomain: true
block "matomedane.jp"
block "1blog.jp"
block "rumors.sub.jp", withoutSubdomain: true
block "comedydouga.com"
block "5chmap.com"
block "antenam.jp"
block "2ch-c.net"
block "ngo-antenna.com"
block "atodeyo.com"
block "t-phantom.jp"
block "yaraon-blog.com"

# site is closed, but it still appears in search results
block "nyfco.org"
block "nicotubers.com"
block "prospectmedicalholdings.com"
block "youtubernews.net"
block "tuberz.net"
block "mitsuya-magazine.com"
block "valenciafashionweek.com"
block "blackshirts.info"
block "documentation-provence.org"
block "idahotvep.org"
block "cambridge-india.org"
block "iketog.com"
block "comisoku.com"
block "vnews.work"
block "vrtuber-news.com"
block "kurojou.com"
block "youtube5ch.com"
block "budou-game.com"
block "vtuber.matomemato.me"
block "vtuber-news.com"
block "jeep-m.jp"
block "vtuber-labo.com"
